name: Java CI with Maven

on:
  [push,pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests=true -B -V
    - name: Upload jar to Artifact
      if: ${{ github.event_name != 'release' && success() }}
      uses: actions/upload-artifact@v4
      with:
          name: einvoice
          path: target/*.jar
  
